
  pnr_search:  http://pnrstage.railyatri.in/api/pnr/journey/
  food_option: http://test.railyatri.in/ecomm/all-vendors-based-on-a-train.json
  opt_food_option: http://test.railyatri.in/ecomm/display-all-stations-for-food.json
  update_order_status: http://test.railyatri.in/ecomm/get-and-update-order-status/
  update_user_email: http://test.railyatri.in/ecomm/update-customer-email
  save_order: http://test.railyatri.in/ecomm/save_order.json
  user_wallet: http://test.railyatri.in//user_wallets/get_wallet_balance.json
  user_wallet_detail: http://test.railyatri.in/user_wallets/get_user_wallet_details
  user_points: http://test.railyatri.in/get_user_point_details.json
  save_payment: http://test.railyatri.in/ecomm/ry-web-create-payment-details.json
  get_order_details: http://test.railyatri.in/ecomm/get-order-details/
  block_ticket_url: http://test.railyatri.in/redbus/block-passenger-ticket.json
  confirm_ticket_status: http://test.railyatri.in/web-confirm-ticket
  city_list_url: http://test.railyatri.in/redbus/source-city-list.json
  get_available_bus_trips: http://test.railyatri.in/redbus/get-available-trips.json
  get_trip_details: http://test.railyatri.in/redbus/get-trip-details
  pay_by_wallet: http://test.railyatri.in/citrushcheckout/pay_by_wallet
  api_base_url: http://test.railyatri.in
  send_invoice_mail: http://test.railyatri.in/citrushcheckout/send-invoice-mail
  online_to_cod: http://test.railyatri.in/ecomm/verify-online-to-cod-order.json?
  coupon_list: http://test.railyatri.in/ecomm/get-coupon.json
  coupon_apply: http://test.railyatri.in//ecomm/coupon-discount-info.json?
  coach_position: http://test.railyatri.in/api/coach_position/
  food_stations: http://test.railyatri.in/ecomm/food-active-stations.json
  menu_at_stations: http://test.railyatri.in/ecomm/all-menu-in-a-station.json?
  validate_stations: http://test.railyatri.in/ecomm/station-validation-and-create-journey.json?
  generate_bill: https://payment-test.railyatri.in/citrus/generate_bill?
  return_url: http://payment-test.railyatri.in/hook/get-payment
  cashback_configuration: http://test.railyatri.in/cashback-configuration
  cashback_calculation: http://test.railyatri.in/get-cashback-calculation-for_bus.json?
  get_bus_coupon: http://test.railyatri.in/ecomm/get-coupon.json?ecomm_type=1
  trip_detail: http://test.railyatri.in/redbus/bus-trip-detail.json?bus_trip_id=
  list_agents: http://trainticketapi-stage.railyatri.in/api/train-ticket/list-agents?
  paytm_return_url: http://payment-test.railyatri.in/return-url
  generate_checksum: http://payment-test.railyatri.in/generate-checksum?payment_provider=
  virtual_journey: http://test.railyatri.in//ecomm/create-journey-for-food.json
  validate_order: http://test.railyatri.in/ecomm/api/validate-ecomm-cancellation?
  time_table: http://test.railyatri.in/m/schedule/
  live_arr_dep: https://livestatus.railyatri.in/api/train_at_station/
  train_bw_station: http://test.railyatri.in/api/trains-between-station.json
  runing_status: https://livestatus.railyatri.in/api/train_eta_data/
  update_platform: http://test.railyatri.in/instant_platform_update.json
